FROM python:latest

RUN mkdir -p /usr/src/app1

WORKDIR /usr/src/app1

RUN mkdir -p ./uploads/

COPY requirements.txt app1.py ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5001

CMD ["python", "app1.py"]