version: '3.1'

services:
    db:
        image: postgres:12
        ports:
        - "5432:5432"
        environment: 
        - POSTGRES_PASSWORD=grunger
        container_name: my-postgres

    adm:
        image: adminer
        ports: 
        - 8080:8080
        container_name: my-adminer