version: "3.8"

services:
    dbase:
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=grunger
        container_name: my-postgres

    adm:
        image: adminer
        depends_on:
            - dbase
        ports:
            - 8080:8080
        container_name: my-adminer

    api:
        build:
            context: .
        image: amareyah/webapp:01
        depends_on:
            - dbase
        ports:
            - "5000:5000"
        container_name: webapp
        environment:
            - DB_URI=postgresql://postgres:grunger@dbase/postgres
        volumes:
            #- type: bind
              #source: ./uploads
              #target: /usr/src/webapp/uploads/
            - type: volume
              source: my_volume
              target: /usr/src/webapp/uploads/
volumes:
    my_volume:
